### ISSUE TITLE
Breaks bot tag on memberlist

### ISSUE THREAD

**Issue by Uranite** [KraXen72/harmony-discord#1]
![image](https://user-images.githubusercontent.com/62639703/90234491-f43f7600-de49-11ea-96b8-c660c6b0d8b6.png)
Can you please fix it? I really love your theme, thanks!

**Comment by Uranite** [comment]
And also, your deepblue theme does this too

**Comment by Uranite** [comment]
![image](https://user-images.githubusercontent.com/62639703/90235288-40d78100-de4b-11ea-8f89-ac951c6e0069.png)
And also, is this supposed to happend? (No server group background) If it is, can you make a version with group background? Thanks!

**Comment by KraXen72** [comment]
yeah ill look into the bot tag, but the server backg is kind of on purpose, but i can add a background to it - but it will most likely be the same for all server folders

**Comment by KraXen72** [comment]
thanks for using my theme tho :)

**Comment by KraXen72** [comment]
fixed both

**Comment by Uranite** [comment]
thanks, your theme is awesome!

**Comment by KraXen72** [comment]
love to hear it someone uses it! thanks! ill close this now.
