### ISSUE TITLE
bot tag broken when u click bot in userlist and viewing profile

### ISSUE THREAD

**Issue by Uranite** [KraXen72/harmony-discord#2]
![image](https://user-images.githubusercontent.com/62639703/91033909-565c6000-e62e-11ea-8a0c-c5245de58d42.png)
like this and also on profile

**Comment by KraXen72** [comment]
ok ill try to fix this

**Comment by KraXen72** [comment]
fixed

**Comment by Uranite** [comment]
cool ty
